button_list = [
    ("Airds Point", "layout/airds_point.png", "map/airds_point.png"),
    ("An Camus", "layout/an_camus.png", "map/an_camus.png"),
    ("Ardintoul", "layout/ardintoul.png", "map/ardintoul.png"),
    ("Ardmair", "layout/ardmair.png", "map/ardmair.png"),
    ("Ardnish", "layout/ardnish.png", "map/ardnish.png"),
    ("Ardessey", "layout/ardessey.png", "map/ardessey.png"),
    ("BDNC", "layout/bdnc.png", "map/bdnc.png"),
    ("Cairidth", "layout/cairidth.png", "map/cairidth.png"),
    ("Carradale", "layout/carradale.png", "map/carradale.png"),
    ("Colonsay", "layout/colonsay.png", "map/colonsay.png"),
    ("Duich", "layout/duich.png", "map/duich.png"),
    ("Gorsten", "layout/gorsten.png", "map/gorsten.png"),
    ("Greshornish", "layout/greshornish.png", "map/greshornish.png"),
    ("Greanem", "layout/greanem.png", "map/greanem.png"),
    ("Groatay", "layout/groatay.png", "map/groatay.png"),
    ("Grey Horse Channel", "layout/grey_horse_channel.png", "map/grey_horse_channel.png"),
    ("Hellisay", "layout/hellisay.png", "map/hellisay.png"),
    ("Invasion Bay", "layout/invasion_bay.png", "map/invasion_bay.png"),
    ("Inverawe", "layout/inverawe.png", "map/inverawe.png"),
    ("Kingairloch", "layout/kingairloch.png", "map/kingairloch.png"),
    ("Laga Bay", "layout/laga_bay.png", "map/laga_bay.png"),
    ("Leven", "layout/leven.png", "map/leven.png"),
    ("Linhe", "layout/linhe.png", "map/linhe.png"),
    ("Loch Alsh", "layout/loch_alsh.png", "map/loch_alsh.png"),
    ("Loch Hourn", "layout/loch_hourn.png", "map/loch_hourn.png"),
    ("Loch Shell", "layout/loch_shell.png", "map/loch_shell.png"),
    ("Loch Skipport", "layout/loch_skipport.png", "map/loch_skipport.png"),
    ("MacLeans Nose", "layout/macleans_nose.png", "map/macleans_nose.png"),
    ("Marulaig Bay", "layout/marulaig_bay.png", "map/marulaig_bay.png"),
    ("Moal Ban", "layout/moal_ban.png", "map/moal_ban.png"),
    ("Muck", "layout/muck.png", "map/muck.png"),
    ("NorthShore", "layout/northshore.png", "map/northshore.png"),
    ("PNG", "layout/png.png", "map/png.png"),
    ("PNC", "layout/pnc.png", "map/pnc.png"),
    ("Port na Mine", "layout/port_na_mine.png", "map/port_na_mine.png"),
    ("Portnalong", "layout/portnalong.png", "map/portnalong.png"),
    ("Rum", "layout/rum.png", "map/rum.png"),
    ("Sailean Ruadh", "layout/sailean_ruadh.png", "map/sailean_ruadh.png"),
    ("Sconser Quarry", "layout/sconser_quarry.png", "map/sconser_quarry.png"),
    ("Scalpay", "layout/scalpay.png", "map/scalpay.png"),
    ("Seaforth", "layout/seaforth.png", "map/seaforth.png"),
    ("Stulaigh", "layout/stulaigh.png", "map/stulaigh.png"),
    ("Sunart", "layout/sunart.png", "map/sunart.png"),
    ("SW Shuna", "layout/sw_shuna.png", "map/sw_shuna.png"),
    ("Tabhaigh", "layout/tabhaigh.png", "map/tabhaigh.png"),
    ("Torridon", "layout/torridon.png", "map/torridon.png"),
    ("Trilleachan Mor", "layout/trilleachan_mor.png", "map/trilleachan_mor.png"),
    ("Wester Ross", "layout/wester_ross.png", "map/wester_ross.png"),
    ("West Loch Tarbert", "layout/west_loch_tarbert.png", "map/west_loch_tarbert.png")
]
